---
apiVersion: v1
kind: Service
metadata:
  name: nginxauth
  labels:
    name: nginxauth
spec:
  ports:
    - port: {{ .Values.nginxAuth.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    name: {{ .Values.nginxAuth.host }}
